<?php
/* Template Name: 3D Printing Quote */
get_header();
$sent = isset($_GET['quote_sent']);
$error = isset($_GET['quote_error']);
$quote_materials = get_terms(array('taxonomy' => 'tokraft_material', 'hide_empty' => false, 'orderby' => 'name', 'order' => 'ASC'));
if (is_wp_error($quote_materials)) {
    $quote_materials = array();
}
$requested_material = isset($_GET['material']) ? sanitize_title(wp_unslash($_GET['material'])) : '';
?>
<section class="page-hero"><div class="page-hero-inner"><div class="eyebrow">Print service / Request a quote</div><h1>Tell us what your part needs.</h1><p>Share your file and production preferences in one place. We will review manufacturability and confirm the final price and schedule before anything is made.</p></div></section>
<div class="quote-layout">
    <form class="quote-form" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="tokraft_quote">
        <?php wp_nonce_field('tokraft_quote', 'tokraft_quote_nonce'); ?>
        <?php if ($sent) : ?><div class="notice">Thanks - your request is with our production team. We will review the file and reply with a confirmed quote.</div><?php endif; ?>
        <?php if ($error) : ?><div class="notice" style="border-color:#a93b31;background:#fff1f0;color:#7d271f;">Please complete the required details and upload a supported model file if you have one.</div><?php endif; ?>
        <section class="form-step"><div class="step-heading"><span class="step-number">1</span><div><h2>Upload your model</h2><p>Our team checks every file before production. Add any supported model you already have.</p></div></div><label class="upload-zone"><input type="file" id="model-file" name="model_file" accept=".stl,.3mf,.step,.stp,.obj"><span><span class="upload-icon">⇧</span><strong>Drop your model here or choose a file</strong><span>STL, 3MF, STEP, STP or OBJ · up to your server upload limit</span></span></label><p id="file-status" class="file-status" aria-live="polite"></p></section>
        <section class="form-step"><div class="step-heading"><span class="step-number">2</span><div><h2>Choose print details</h2><p>Set your preferences; a question mark explains what each setting affects.</p></div></div>
            <div class="form-grid"><div class="field"><label for="material">Material</label><select id="material" name="material">
                <?php if ($quote_materials) : foreach ($quote_materials as $index => $material) :
                    $description = get_term_meta($material->term_id, '_tokraft_material_short_description', true);
                    $is_selected = $requested_material ? $requested_material === $material->slug : 0 === $index; ?>
                    <option value="<?php echo esc_attr($material->name); ?>" data-estimate="<?php echo esc_attr(tokraft_material_quote_rate($material)); ?>" <?php selected($is_selected); ?>><?php echo esc_html($material->name . ($description ? ' - ' . $description : '')); ?></option>
                <?php endforeach; else : ?>
                    <option value="PLA" data-estimate="24">PLA - clean detail and everyday use</option><option value="PETG" data-estimate="29">PETG - durable and weather resistant</option><option value="ASA" data-estimate="32">ASA - UV and weather resistant</option><option value="TPU" data-estimate="37">TPU - flexible and impact absorbing</option>
                <?php endif; ?>
            </select></div><div class="field"><label for="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="1" value="1" required></div><div class="field"><span class="field-label">Color</span><div class="color-choice" aria-label="Color"><label class="choice"><input type="radio" name="color" value="Natural" checked><span style="background:#e8e7df" title="Natural"></span></label><label class="choice"><input type="radio" name="color" value="Black"><span style="background:#18202b" title="Black"></span></label><label class="choice"><input type="radio" name="color" value="Blue"><span style="background:#1a5796" title="Blue"></span></label><label class="choice"><input type="radio" name="color" value="White"><span style="background:#fff" title="White"></span></label><label class="choice"><input type="radio" name="color" value="Custom"><span style="background:linear-gradient(135deg,#d79c2d,#d65d60,#1a5796)" title="Custom"></span></label></div></div></div>
            <div style="margin-top:31px"><div class="range-field"><div class="range-top"><label class="field-label" for="infill">Infill density <button class="help" type="button" data-help="Infill is the pattern inside a printed part. More infill increases strength and material use, which also increases cost and printing time.">?</button></label><output class="range-value" for="infill" id="infill-value">20%</output></div><input type="range" id="infill" name="infill" min="10" max="100" step="5" value="20" data-output="infill-value" data-suffix="%"><div class="range-impact" id="infill-impact">Balanced strength, efficient material use and standard lead time.</div></div><div class="range-field"><div class="range-top"><label class="field-label" for="walls">Wall perimeters <button class="help" type="button" data-help="Walls are the outer shells of a part. Extra walls improve strength and surface durability, especially around holes and load-bearing features.">?</button></label><output class="range-value" for="walls" id="walls-value">3 walls</output></div><input type="range" id="walls" name="walls" min="2" max="6" step="1" value="3" data-output="walls-value" data-suffix=" walls"><div class="range-impact" id="walls-impact">A dependable balance for functional prototypes.</div></div><div class="range-field"><div class="range-top"><label class="field-label" for="layer-height">Layer height / detail <button class="help" type="button" data-help="Thinner layers capture smoother curves and finer features. They also make the print take longer; larger layers are faster and more economical.">?</button></label><output class="range-value" for="layer-height" id="layer-height-value">0.20 mm</output></div><input type="range" id="layer-height" name="layer_height" min="0.12" max="0.32" step="0.04" value="0.20" data-output="layer-height-value" data-suffix=" mm"><div class="range-impact" id="layer-impact">Standard detail with a balanced production time.</div></div></div>
            <div class="form-grid"><div class="field"><span class="field-label">Support material <button class="help" type="button" data-help="Supports are temporary structures used under overhangs. They allow complex geometry but can leave small marks where they are removed.">?</button></span><div class="toggle-row"><label class="choice"><input type="radio" name="support" value="No" checked><span>No support</span></label><label class="choice"><input type="radio" name="support" value="Yes"><span>Use support</span></label></div></div><div class="field"><span class="field-label">Brim or raft <button class="help" type="button" data-help="A brim or raft improves bed adhesion for tall, narrow or warp-prone parts. It is removed after the print is complete.">?</button></span><div class="toggle-row"><label class="choice"><input type="radio" name="adhesion" value="None" checked><span>None</span></label><label class="choice"><input type="radio" name="adhesion" value="Brim / Raft"><span>Brim / raft</span></label></div></div></div>
        </section>
        <section class="form-step"><div class="step-heading"><span class="step-number">3</span><div><h2>Project & contact</h2><p>Tell us anything that affects how the part must fit, work or look.</p></div></div><div class="form-grid"><div class="field"><label for="contact-name">Name</label><input id="contact-name" name="contact_name" autocomplete="name" required></div><div class="field"><label for="contact-email">Email</label><input id="contact-email" name="contact_email" type="email" autocomplete="email" required></div><div class="field"><label for="company">Company <small>(optional)</small></label><input id="company" name="company" autocomplete="organization"></div><div class="field"><label for="project-type">Project type</label><select id="project-type" name="project_type"><option>Prototype</option><option>Replacement part</option><option>Small production run</option><option>Product development</option></select></div></div><div class="field" style="margin-top:22px"><label for="notes">Tolerances, assemblies or special requirements</label><textarea id="notes" name="notes" placeholder="For example: critical fit dimensions, threaded inserts, multiple parts that must assemble, finish expectations or deadline."></textarea></div><label class="terms"><input type="checkbox" required><span>I understand this is a request for quotation. The shown estimate and production time are indicative only; a final quote requires a file review.</span></label><button class="btn btn-primary" type="submit">Submit quote request <span aria-hidden="true">→</span></button></section>
    </form>
    <aside class="quote-summary" aria-live="polite"><div class="eyebrow" style="color:var(--gold-light)">Live estimate</div><h2>Your print summary</h2><ul class="summary-list"><li><span>Material</span><b id="summary-material">PLA</b></li><li><span>Color</span><b id="summary-color">Natural</b></li><li><span>Quantity</span><b id="summary-quantity">1 part</b></li><li><span>Infill</span><b id="summary-infill">20%</b></li><li><span>Walls</span><b id="summary-walls">3</b></li><li><span>Layer height</span><b id="summary-layer">0.20 mm</b></li></ul><div class="estimate"><span>Estimated range</span><strong id="estimate-price">$24–$34</strong></div><p class="summary-disclaimer">This is an initial estimate, not a final offer. Model volume, orientation, geometry and post-processing are confirmed by our team after file review.</p></aside>
</div>
<dialog class="modal" id="help-modal"><button class="modal-close" type="button" aria-label="Close">×</button><h3 id="help-title">Print setting</h3><p id="help-copy"></p><button class="btn btn-primary btn-small" type="button">Got it</button></dialog>
<?php get_footer(); ?>
